// PDF Generator for quiz export with Arabic support

import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { PerformanceData, QuestionResult } from './performance-analyzer';

// Add Arabic font support (using built-in fonts for now)
// For better Arabic support, you can add custom fonts later

export function generateQuizPDF(performance: PerformanceData, weakAreas: string[]): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Quiz Results / نتائج الاختبار', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;

  // Quiz Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text(performance.quizTitle, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;

  // Date
  doc.setFontSize(10);
  doc.text(`Date: ${new Date(performance.completedAt).toLocaleDateString('ar-EG')}`, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;

  // Performance Summary Box
  doc.setFillColor(254, 240, 138);
  doc.roundedRect(15, yPosition, pageWidth - 30, 30, 3, 3, 'F');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Score: ${performance.score} / ${performance.totalQuestions}`, 20, yPosition + 10);
  doc.text(`Percentage: ${performance.percentage}%`, 20, yPosition + 20);
  
  yPosition += 40;

  // Weak Areas Section
  if (weakAreas.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Areas to Review:', 15, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    weakAreas.forEach((area, index) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
      }
      // Remove Arabic text for PDF compatibility, use English
      const cleanArea = area.replace(/[^\x00-\x7F]/g, '');
      doc.text(`${index + 1}. ${cleanArea || 'Review this topic'}`, 20, yPosition);
      yPosition += 6;
    });

    yPosition += 10;
  }

  // Questions and Answers
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  
  if (yPosition > pageHeight - 40) {
    doc.addPage();
    yPosition = 20;
  }
  
  doc.text('Questions & Answers:', 15, yPosition);
  yPosition += 10;

  performance.results.forEach((result, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = 20;
    }

    // Question number and status
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    const status = result.isCorrect ? '✓' : '✗';
    const statusColor: [number, number, number] = result.isCorrect ? [34, 197, 94] : [239, 68, 68];
    
    doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.text(`${status} Question ${index + 1}`, 15, yPosition);
    doc.setTextColor(0, 0, 0);
    
    yPosition += 7;

    // Question text (remove Arabic for compatibility)
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const questionText = result.question.replace(/[^\x00-\x7F]/g, '') || `Question ${index + 1}`;
    const questionLines = doc.splitTextToSize(questionText, pageWidth - 30);
    doc.text(questionLines, 20, yPosition);
    yPosition += questionLines.length * 5 + 3;

    // Your answer
    doc.setFont('helvetica', 'bold');
    doc.text('Your Answer:', 20, yPosition);
    doc.setFont('helvetica', 'normal');
    const userAnswerText = result.userAnswer.replace(/[^\x00-\x7F]/g, '') || 'No answer';
    doc.text(userAnswerText, 50, yPosition);
    yPosition += 6;

    // Correct answer (if wrong)
    if (!result.isCorrect) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(34, 197, 94);
      doc.text('Correct Answer:', 20, yPosition);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');
      const correctAnswerText = result.correctAnswer.replace(/[^\x00-\x7F]/g, '') || 'See notes';
      doc.text(correctAnswerText, 50, yPosition);
      yPosition += 6;
    }

    yPosition += 8;
  });

  // Footer on last page
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text('Generated by Quiz App', pageWidth / 2, pageHeight - 5, { align: 'center' });
  }

  // Save the PDF
  const fileName = `quiz-${performance.quizTitle.replace(/[^\w\s]/gi, '')}-${new Date().getTime()}.pdf`;
  doc.save(fileName);
}

// Alternative: Generate simple text-based PDF for better Arabic support
export function generateSimpleQuizPDF(performance: PerformanceData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(20);
  doc.text('Quiz Results', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Score
  doc.setFontSize(14);
  doc.text(`Score: ${performance.score}/${performance.totalQuestions} (${performance.percentage}%)`, pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Questions
  doc.setFontSize(10);
  performance.results.forEach((result, idx) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    const mark = result.isCorrect ? '[✓]' : '[✗]';
    doc.text(`${mark} Q${idx + 1}: ${result.question.substring(0, 60)}...`, 15, y);
    y += 7;
  });

  doc.save(`quiz-results-${Date.now()}.pdf`);
}
